### ISSUE TITLE
Want to create a navbar for the page 

### ISSUE THREAD

**Issue by aadrikasingh18** [aman34503/Go-Airbnb#10]
I want to work on this issue under JWOC

**Comment by aman34503** [comment]
Great! which framework / library are you used for creating navbar?

**Comment by aadrikasingh18** [comment]
Can I start working on this issue after my 2 PRs are merged ? Cause I already have 2 issues I just saw?

**Comment by aadrikasingh18** [comment]
Pls don't assign it to anyone else

**Comment by dilroseR** [comment]
@aman34503 May I know how to run this project on my machine since it is not mentioned in README.md.
Also, let me know on which page do you need the navbar and what all links you need on them.
I would like to work on this under JWOC after getting these details.

**Comment by aadrikasingh18** [comment]
@aman34503 My other 2 PR's will merge today then I will work on this issue.

**Comment by aadrikasingh18** [comment]
I am thinking of using React Js

**Comment by aman34503** [comment]
> first you clone the repo
open in your Ide and just run two commands
npm i & npm start
it will automatically runs in your browser 


> @aman34503 May I know how to run this project on my machine since it is not mentioned in README.md. Also, let me know on which page do you need the navbar and what all links you need on them. I would like to work on this under JWOC after getting these details.

**Comment by aman34503** [comment]
@dilroseR you have to raise another issue in which you are worked on!
