### ISSUE TITLE
Readme Update :

### ISSUE THREAD

**Issue by ayush-sleeping** [aman34503/Go-Airbnb#11]
Add labels ,
Add Table of content ,
Add Tech-Stack used ,
Add Open Source programs this repo has been part of ,
Add Contributors section ,
Add Feedback ,

<br>

All things categorize it, In a systematic way ......

**Comment by ayush-sleeping** [comment]
Hey @aman34503 , I want to work on this issue and want to make the Readme file of this Open Source project more Beginner friendly and want to add more things . 
<br>

Under JWOC'22

**Comment by aman34503** [comment]
Great ! you can start working on this
