### ISSUE TITLE
[Feature]: want to create a user profile page #JWOC

### ISSUE THREAD

**Issue by mnnkhndlwl** [aman34503/Go-Airbnb#15]
### Is your feature request related to a problem? Please describe.

when user clicks on the profile picture he/she will be redirected to a profile page where user can see all his details

**Comment by mnnkhndlwl** [comment]
i want to work on this issue under jwoc

**Comment by mnnkhndlwl** [comment]
@aman34503

**Comment by aman34503** [comment]
sure! Just make sure The Page is Responsive

**Comment by mnnkhndlwl** [comment]
![image](https://user-images.githubusercontent.com/75252077/152565275-fb1f40c9-3f07-42a1-8e8c-c557d12452ef.png)
@aman34503 i have just cloned it and i am getting this error

**Comment by mnnkhndlwl** [comment]
@aman34503 I think a contributor has messed up with the actual code
should i add header.css from project history

**Comment by mnnkhndlwl** [comment]
@aman3450

**Comment by aman34503** [comment]
yes sure!
