### ISSUE TITLE
[Feature]: User Login & Signup page

### ISSUE THREAD

**Issue by Mainakroy050** [aman34503/Go-Airbnb#28]

**Comment by ronitblenz** [comment]
If its Jwoc issue, could you mention the difficulty tag and jwoc tag? Then, I am wiling to work on this issue

**Comment by aman34503** [comment]
sure @ronitblenz

**Comment by ronitblenz** [comment]
Please upgrade the label to medium, its not an easy issue.. I hope you understand

**Comment by ronitblenz** [comment]
I have made a PR, plz change the issue to Medium and merge my PR

**Comment by aman34503** [comment]
Kindly Go through the Documentation and Check first!

**Comment by mnnkhndlwl** [comment]
@aman34503 i saw the pr of ronitblenz 
i can use his signin/signup page and using react router i can make his signon/signup page usable in your project
if you like assign me this issue and add hard label to it

**Comment by ronitblenz** [comment]
If that is the case, plz merge my PR. @aman34503 can handle the rest

**Comment by aman34503** [comment]
@mnnkhndlwl no you don't use this, but you raise an another issue and start working on this!

**Comment by ronitblenz** [comment]
Merging this could have helped both of us... Anyways..no problem

**Comment by mnnkhndlwl** [comment]
@aman34503 i have raised my issue you can close this issue now
