### ISSUE TITLE
[Bug]: Login Page and Settings Page aren't responsive

### ISSUE THREAD

**Issue by Shruti025** [aman34503/Go-Airbnb#39]
### Describe the bug

The Login Page and the Settings(Profile) page are not responsive.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/72005584/154678819-b3cc3883-b005-4c68-b21e-3240810f78c2.png)

![image](https://user-images.githubusercontent.com/72005584/154678004-0ec193cd-d2d3-4c32-a384-0751ec85300b.png)

**Comment by aman34503** [comment]
Sure!
