### ISSUE TITLE
[Feature]: The footer section of "Stays nearby" page is not according to the full web page size .

### ISSUE THREAD

**Issue by sayan404** [aman34503/Go-Airbnb#41]
![Screenshot 2022-02-18 180052](https://user-images.githubusercontent.com/95490367/154683609-71871500-9271-40c5-b026-123a65fd5ece.png)

**Comment by Shruti025** [comment]
hey I have already opened an issue for this bug and #42 as well :)

**Comment by Shruti025** [comment]
It's totally cool @sayan404, thank you for cooperating :)
