### ISSUE TITLE
banner info is showing over the card

### ISSUE THREAD

**Issue by mnnkhndlwl** [aman34503/Go-Airbnb#8]
![image](https://user-images.githubusercontent.com/75252077/151925381-1a481c96-b357-40d9-aaec-25fe7205166b.png)
can i fix this issue under jwoc
i will align it with image and it would look good

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by mnnkhndlwl** [comment]
@aman34503 sir assign it to me

**Comment by mnnkhndlwl** [comment]
Sir you assigned it to yourself and closed this issue. Why?

**Comment by aman34503** [comment]
now its perfect ! You can start working on this show.

**Comment by mnnkhndlwl** [comment]
@aman34503 sir apne ek hi issue do logo ko assign kardiya 
rules ke according jisme issue raise kiya hai hai usse assign karna hai or sir jwoc or difficulty ka tag or add kardo

**Comment by mnnkhndlwl** [comment]
@aman34503 sir I have fixed this issue please check that and also add relevant labels to this issue so that my points can be counted
